In [1]:
import pandas as pd

df = pd.read_csv("https://ourworldindata.org/grapher/gdp-per-capita-worldbank.csv?v=1&csvType=full&useColumnShortNames=true", storage_options = {'User-Agent': 'Our World In Data data fetch/1.0'})

In [2]:
df=df[df['Year']==2023]
df=df[['Code','ny_gdp_pcap_pp_kd']]
df.rename(columns={'ny_gdp_pcap_pp_kd': 'GDP','Code':'LOCATION'}, inplace=True)
df

      LOCATION         GDP
23         AFG   1992.4244
57         ALB  18244.2930
91         DZA  15159.3240
125        AND  64631.2970
159        AGO   7244.8930
...        ...         ...
6926       VUT   3118.3960
6960       VNM  13491.8800
6994  OWID_WRL  20670.9410
7028       ZMB   3673.4841
7062       ZWE   3442.2512

[206 rows x 2 columns]

In [3]:
df2=pd.read_csv("housingn.csv")

In [4]:
df2.columns

Index(['STRUCTURE', 'STRUCTURE_ID', 'STRUCTURE_NAME', 'ACTION', 'LOCATION',
       'Country', 'INDICATOR', 'Indicator', 'MEASURE', 'Measure', 'INEQUALITY',
       'Inequality', 'OBS_VALUE', 'Observation Value', 'OBS_STATUS',
       'Observation Status', 'UNIT_MEASURE', 'Unit of Measures', 'UNIT_MULT',
       'Multiplier', 'BASE_PER', 'Base reference period'],
      dtype='object')

In [5]:


df2=df2.drop(columns=['STRUCTURE','STRUCTURE_ID','STRUCTURE_NAME','ACTION','MEASURE','Measure','Inequality','Observation Value','OBS_STATUS','Observation Status','Unit of Measures',
                   'UNIT_MULT','Multiplier','BASE_PER','Base reference period','UNIT_MEASURE'])

In [6]:
df2.head()

  LOCATION  Country INDICATOR                 Indicator INEQUALITY  OBS_VALUE
0      AUT  Austria   JE_LMIS  Labour market insecurity        TOT        2.3
1      BEL  Belgium   JE_LMIS  Labour market insecurity        TOT        2.4
2      CAN   Canada   JE_LMIS  Labour market insecurity        TOT        3.8
3      CZE  Czechia   JE_LMIS  Labour market insecurity        TOT        2.3
4      DNK  Denmark   JE_LMIS  Labour market insecurity        TOT        4.5

In [7]:
df2[['INDICATOR','Indicator']].groupby(['INDICATOR','Indicator']).size().reset_index(name='counts')

    INDICATOR                                          Indicator  counts
0     CG_SENG  Stakeholder engagement for developing regulations      40
1     CG_VOTO                                      Voter turnout      42
2     EQ_AIRP                                      Air pollution      42
3    EQ_WATER                                      Water quality     126
4     ES_EDUA                             Educational attainment     123
5    ES_EDUEX                                 Years in education     120
6     ES_STCS                                     Student skills     200
7     HO_BASE                 Dwellings without basic facilities      39
8     HO_HISH                                Housing expenditure      38
9     HO_NUMR                                   Rooms per person      39
10     HS_LEB                                    Life expectancy     126
11    HS_SFRH                               Self-reported health     194
12    IW_HADI           Household net adjusted disposable income      36
13    IW_HNFW                               Household net wealth      30
14    JE_EMPL                                    Employment rate     126
15    JE_LMIS                           Labour market insecurity      35
16    JE_LTUR                        Long-term unemployment rate     120
17   JE_PEARN                                  Personal earnings      36
18  PS_FSAFEN                Feeling safe walking alone at night     126
19    PS_REPH                                      Homicide rate     126
20   SC_SNTWS                         Quality of support network     208
21    SW_LIFS                                  Life satisfaction     208
22    WL_EWLH                  Employees working very long hours     120
23    WL_TNOW          Time devoted to leisure and personal care      69

In [8]:
df2=df2.groupby(['LOCATION','Country','INDICATOR']).agg({'OBS_VALUE':'sum'}).reset_index()
df2=df2.pivot(index=['LOCATION','Country'],columns='INDICATOR',values='OBS_VALUE').reset_index()
df2

INDICATOR,LOCATION,Country,CG_SENG,CG_VOTO,EQ_AIRP,EQ_WATER,ES_EDUA,ES_EDUEX,ES_STCS,HO_BASE,...,JE_EMPL,JE_LMIS,JE_LTUR,JE_PEARN,PS_FSAFEN,PS_REPH,SC_SNTWS,SW_LIFS,WL_EWLH,WL_TNOW
0,AUS,Australia,2.7,92.0,6.7,276.0,252.0,61.0,2506.0,NaN,...,219.0,3.1,3.1,55206.0,202.0,2.8,469.0,35.8,37.1,42.81
1,AUT,Austria,1.3,76.0,12.2,275.0,257.0,51.0,2446.0,0.8,...,216.0,2.3,4.0,53132.0,257.0,1.5,465.0,36.4,15.8,43.52
2,BEL,Belgium,2.0,88.0,12.8,237.0,239.0,58.0,2490.0,0.7,...,194.0,2.4,6.9,54327.0,169.0,3.3,451.0,34.4,12.7,46.45
3,BRA,Brazil,2.2,80.0,11.7,211.0,170.0,48.0,2043.0,6.7,...,171.0,NaN,NaN,NaN,134.0,57.8,425.0,31.6,16.5,NaN
4,CAN,Canada,2.9,68.0,7.1,271.0,277.0,51.0,2588.0,0.2,...,210.0,3.8,1.5,55342.0,233.0,3.7,466.0,35.2,9.8,43.64
5,CHE,Switzerland,2.3,45.0,10.1,287.0,267.0,52.0,2468.0,0.0,...,240.0,NaN,5.1,64824.0,258.0,1.0,471.0,37.5,1.1,NaN
6,CHL,Chile,1.3,47.0,23.4,186.0,202.0,52.0,2230.0,9.4,...,168.0,7.0,NaN,26729.0,124.0,7.3,446.0,31.5,22.3,NaN
7,COL,Colombia,1.4,53.0,22.6,245.0,176.0,42.0,2049.0,12.3,...,174.0,NaN,3.4,NaN,149.0,70.2,411.0,29.9,69.0,NaN
8,CRI,Costa Rica,1.8,66.0,17.5,262.0,128.0,NaN,2113.0,2.3,...,164.0,NaN,4.9,NaN,142.0,30.0,422.0,32.6,62.6,NaN
9,CZE,Czechia,1.6,62.0,17.0,268.0,282.0,53.0,2469.0,0.5,...,222.0,2.3,1.7,29885.0,232.0,2.1,483.0,35.2,13.2,NaN
10,DEU,Germany,1.8,76.0,12.0,273.0,259.0,54.0,2515.0,0.1,...,230.0,1.4,3.6,53745.0,228.0,1.1,451.0,37.0,11.4,46.89
11,DNK,Denmark,2.0,85.0,10.0,278.0,245.0,58.0,2505.0,0.5,...,222.0,4.5,2.8,58430.0,256.0,1.6,475.0,37.6,3.3,NaN
12,ESP,Spain,1.8,72.0,10.0,228.0,189.0,54.0,NaN,0.3,...,186.0,15.8,15.2,37922.0,241.0,2.1,470.0,33.3,7.4,47.11
13,EST,Estonia,2.7,64.0,5.9,258.0,272.0,53.0,2632.0,5.7,...,222.0,5.4,3.5,30720.0,240.0,5.6,474.0,32.5,6.6,44.93
14,FIN,Finland,2.2,69.0,5.5,290.0,274.0,59.0,2594.0,0.4,...,217.0,2.2,3.6,46230.0,264.0,3.7,485.0,40.1,10.9,45.52
15,FRA,France,2.1,75.0,11.4,235.0,244.0,50.0,2474.0,0.5,...,195.0,3.1,8.8,45581.0,222.0,1.3,474.0,33.9,23.1,48.52
16,GBR,United Kingdom,3.1,68.0,10.1,246.0,246.0,50.0,2531.0,0.5,...,226.0,3.3,2.7,47147.0,235.0,0.5,464.0,34.3,32.4,44.82
17,GRC,Greece,1.8,58.0,14.5,202.0,229.0,57.0,2279.0,0.4,...,168.0,21.7,33.0,27207.0,207.0,3.0,397.0,29.6,13.1,45.21
18,HUN,Hungary,1.2,70.0,16.7,243.0,257.0,49.0,2391.0,3.5,...,209.0,3.8,3.5,25409.0,222.0,2.7,473.0,31.0,4.4,45.13
19,IRL,Ireland,1.3,63.0,7.8,240.0,256.0,54.0,2553.0,0.2,...,204.0,2.6,3.5,49474.0,229.0,1.4,481.0,35.4,14.2,43.55
20,ISL,Iceland,2.1,81.0,6.4,291.0,228.0,57.0,2391.0,0.0,...,233.0,1.0,2.0,67488.0,256.0,2.0,394.0,30.5,34.6,NaN
21,ISR,Israel,2.5,67.0,19.7,230.0,264.0,47.0,2330.0,NaN,...,201.0,4.6,0.6,39322.0,240.0,4.6,477.0,36.3,42.4,NaN
22,ITA,Italy,2.5,73.0,15.9,232.0,189.0,50.0,2378.0,0.6,...,174.0,8.6,14.5,37769.0,219.0,1.5,448.0,33.2,9.8,48.89
23,JPN,Japan,1.4,53.0,13.7,261.0,NaN,48.0,2562.0,6.4,...,232.0,2.7,2.3,38515.0,231.0,0.6,446.0,30.9,NaN,42.30
24,KOR,Korea,2.9,77.0,27.3,246.0,268.0,52.0,2588.0,2.5,...,198.0,2.9,0.0,41960.0,246.0,2.4,404.0,29.2,NaN,44.40
25,LTU,Lithuania,2.4,57.0,10.5,249.0,281.0,55.0,2394.0,11.8,...,215.0,NaN,7.4,31811.0,187.0,7.5,450.0,32.6,2.9,NaN
26,LUX,Luxembourg,1.7,90.0,10.0,255.0,222.0,45.0,2382.0,0.1,...,201.0,2.2,5.2,65854.0,260.0,0.7,456.0,37.3,8.2,NaN
27,LVA,Latvia,2.2,55.0,12.7,250.0,268.0,55.0,2421.0,11.2,...,215.0,6.3,6.6,29876.0,220.0,11.4,463.0,31.3,5.0,NaN
28,MEX,Mexico,3.2,63.0,20.3,225.0,125.0,46.0,2095.0,25.9,...,180.0,4.0,0.3,16230.0,128.0,82.8,397.0,31.1,77.4,NaN
29,NLD,Netherlands,2.6,79.0,12.2,274.0,243.0,57.0,2491.0,0.1,...,234.0,2.5,2.8,58828.0,250.0,1.8,472.0,37.7,1.0,46.52
30,NOR,Norway,2.2,78.0,6.7,294.0,247.0,55.0,2482.0,0.0,...,225.0,2.8,2.7,55780.0,280.0,1.8,480.0,36.5,4.1,47.06
31,NZL,New Zealand,2.5,82.0,6.0,254.0,243.0,53.0,2529.0,NaN,...,230.0,4.5,1.2,45269.0,199.0,3.9,474.0,36.3,41.9,44.00
32,OECD,OECD - Total,2.1,69.0,14.0,253.0,237.0,53.0,2443.0,3.0,...,199.0,5.1,4.0,49165.0,222.0,7.9,458.0,33.9,30.0,45.11
33,POL,Poland,2.6,68.0,22.8,247.0,280.0,53.0,2568.0,2.3,...,206.0,5.0,1.9,32527.0,214.0,1.6,473.0,31.0,12.2,43.91
34,PRT,Portugal,1.5,49.0,8.3,268.0,166.0,51.0,2467.0,0.9,...,208.0,8.1,6.9,28410.0,250.0,2.1,448.0,30.1,17.0,NaN
35,RUS,Russia,NaN,68.0,11.8,185.0,285.0,49.0,2397.0,13.8,...,210.0,NaN,3.3,NaN,193.0,14.7,448.0,27.6,0.4,NaN
36,SVK,Slovak Republic,3.0,66.0,18.5,244.0,277.0,47.0,2322.0,1.5,...,203.0,8.8,9.0,23619.0,229.0,2.4,476.0,32.9,12.3,NaN
37,SVN,Slovenia,2.5,53.0,17.0,278.0,270.0,55.0,2514.0,0.2,...,213.0,5.9,5.8,41445.0,271.0,1.2,380.0,25.9,16.4,NaN
38,SWE,Sweden,2.0,87.0,5.8,292.0,252.0,59.0,2517.0,0.0,...,226.0,4.4,3.0,47020.0,237.0,3.1,470.0,36.7,2.7,NaN
39,TUR,Türkiye,1.5,86.0,27.1,186.0,125.0,56.0,2337.0,4.9,...,143.0,13.0,10.7,NaN,176.0,3.0,432.0,25.2,72.3,43.48
40,USA,United States,3.1,65.0,7.7,264.0,275.0,52.0,2504.0,0.1,...,201.0,4.2,1.4,69392.0,235.0,18.0,470.0,35.5,30.9,43.66
41,ZAF,South Africa,NaN,66.0,28.5,216.0,144.0,NaN,NaN,35.9,...,116.0,NaN,54.4,NaN,121.0,42.0,451.0,25.3,45.5,NaN

In [9]:
df3=pd.merge(df,df2,how='inner',on='LOCATION')
df3.head()

,LOCATION,GDP,Country,CG_SENG,CG_VOTO,EQ_AIRP,EQ_WATER,ES_EDUA,ES_EDUEX,ES_STCS,...,JE_EMPL,JE_LMIS,JE_LTUR,JE_PEARN,PS_FSAFEN,PS_REPH,SC_SNTWS,SW_LIFS,WL_EWLH,WL_TNOW
0,AUS,59552.880,Australia,2.7,92.0,6.7,276.0,252.0,61.0,2506.0,...,219.0,3.1,3.1,55206.0,202.0,2.8,469.0,35.8,37.1,42.81
1,AUT,65015.133,Austria,1.3,76.0,12.2,275.0,257.0,51.0,2446.0,...,216.0,2.3,4.0,53132.0,257.0,1.5,465.0,36.4,15.8,43.52
2,BEL,64185.848,Belgium,2.0,88.0,12.8,237.0,239.0,58.0,2490.0,...,194.0,2.4,6.9,54327.0,169.0,3.3,451.0,34.4,12.7,46.45
3,BRA,19018.238,Brazil,2.2,80.0,11.7,211.0,170.0,48.0,2043.0,...,171.0,NaN,NaN,NaN,134.0,57.8,425.0,31.6,16.5,NaN
4,CAN,55918.930,Canada,2.9,68.0,7.1,271.0,277.0,51.0,2588.0,...,210.0,3.8,1.5,55342.0,233.0,3.7,466.0,35.2,9.8,43.64

In [10]:
df3.columns

Index(['LOCATION', 'GDP', 'Country', 'CG_SENG', 'CG_VOTO', 'EQ_AIRP',
       'EQ_WATER', 'ES_EDUA', 'ES_EDUEX', 'ES_STCS', 'HO_BASE', 'HO_HISH',
       'HO_NUMR', 'HS_LEB', 'HS_SFRH', 'IW_HADI', 'IW_HNFW', 'JE_EMPL',
       'JE_LMIS', 'JE_LTUR', 'JE_PEARN', 'PS_FSAFEN', 'PS_REPH', 'SC_SNTWS',
       'SW_LIFS', 'WL_EWLH', 'WL_TNOW'],
      dtype='object')

In [11]:
dfn=pd.read_csv("indicadores_normalizados.csv")
dfn.head()

,LOCATION,CG_SENG,CG_VOTO,EQ_AIRP,EQ_WATER,ES_EDUA,ES_EDUEX,ES_STCS,HO_BASE,HO_HISH,...,JE_LMIS,JE_LTUR,JE_PEARN,PS_FSAFEN,PS_REPH,SC_SNTWS,SW_LIFS,WL_EWLH,WL_TNOW,ny_gdp_pcap_pp_kd
0,AUS,0.75,1.000000,0.947826,0.833333,0.792453,1.000000,0.785714,NaN,0.629921,...,0.898551,0.944134,0.733155,0.264151,0.973684,0.761905,0.733333,0.460967,0.890295,0.384894
1,AUT,0.05,0.659574,0.708696,0.833333,0.830189,0.500000,0.722222,0.977716,0.519685,...,0.937198,0.927374,0.694142,0.867925,0.988722,0.714286,0.766667,0.193309,0.827004,0.430735
2,BEL,0.40,0.914894,0.682609,0.472222,0.716981,0.833333,0.793651,0.980501,0.582677,...,0.932367,0.871508,0.716621,0.301887,0.966165,0.619048,0.633333,0.156134,0.400844,0.423775
3,BRA,0.50,0.744681,0.730435,0.222222,0.283019,0.333333,0.000000,0.813370,NaN,...,NaN,NaN,NaN,0.094340,0.293233,0.285714,0.400000,0.204461,NaN,0.044713
4,CAN,0.85,0.489362,0.930435,0.777778,0.943396,0.500000,0.928571,0.994429,0.354331,...,0.864734,0.972067,0.735713,0.716981,0.962406,0.761905,0.700000,0.118959,0.801688,0.354397

In [12]:
dfn.columns

Index(['LOCATION', 'CG_SENG', 'CG_VOTO', 'EQ_AIRP', 'EQ_WATER', 'ES_EDUA',
       'ES_EDUEX', 'ES_STCS', 'HO_BASE', 'HO_HISH', 'HO_NUMR', 'HS_LEB',
       'HS_SFRH', 'IW_HADI', 'IW_HNFW', 'JE_EMPL', 'JE_LMIS', 'JE_LTUR',
       'JE_PEARN', 'PS_FSAFEN', 'PS_REPH', 'SC_SNTWS', 'SW_LIFS', 'WL_EWLH',
       'WL_TNOW', 'ny_gdp_pcap_pp_kd'],
      dtype='object')

In [13]:
dfn['Housing'] = dfn[['HO_HISH', 'HO_NUMR', 'HS_LEB']].mean(axis=1)
dfn['Income'] = dfn[['IW_HADI', 'IW_HNFW']].mean(axis=1)
dfn['Jobs'] = dfn[['JE_EMPL', 'JE_LMIS', 'JE_LTUR','JE_PEARN']].mean(axis=1)
dfn['Community'] = dfn[['SC_SNTWS']].mean(axis=1)
dfn['Education'] = dfn[['ES_EDUA','ES_EDUEX', 'ES_STCS']].mean(axis=1)
dfn['Enviroment'] = dfn[['EQ_AIRP', 'EQ_WATER']].mean(axis=1)
dfn['Civic engagement'] = dfn[['CG_SENG', 'CG_VOTO']].mean(axis=1)
dfn['Health'] = dfn[['HS_LEB','HS_SFRH']].mean(axis=1)
dfn['Life Satisfaction'] = dfn[['SW_LIFS']].mean(axis=1)
dfn['Safety'] = dfn[['PS_FSAFEN', 'PS_REPH']].mean(axis=1)
dfn['Work Life Balance'] = dfn[['WL_EWLH','WL_TNOW']].mean(axis=1)
df_final=dfn[['LOCATION','Housing','Income','Community','Education','Enviroment','Civic engagement','Health','Life Satisfaction','Safety','Work Life Balance','ny_gdp_pcap_pp_kd']]
df_final.head()

,LOCATION,Housing,Income,Community,Education,Enviroment,Civic engagement,Health,Life Satisfaction,Safety,Work Life Balance,ny_gdp_pcap_pp_kd
0,AUS,0.780307,0.596762,0.761905,0.859389,0.890580,0.875000,0.928983,0.733333,0.618918,0.675631,0.384894
1,AUT,0.591958,0.464477,0.714286,0.684137,0.771014,0.354787,0.776958,0.766667,0.928323,0.510156,0.430735
2,BEL,0.718772,0.519196,0.619048,0.781322,0.577415,0.657447,0.806706,0.633333,0.634026,0.278489,0.423775
3,BRA,0.579208,NaN,0.285714,0.205451,0.476329,0.622340,0.579208,0.400000,0.193786,0.204461,0.044713
4,CAN,0.746823,0.531429,0.761905,0.790656,0.854106,0.669681,0.943069,0.700000,0.839694,0.460323,0.354397

In [14]:
df_final=pd.merge(df_final,df,on='LOCATION')
df_final.head()

,LOCATION,Housing,Income,Community,Education,Enviroment,Civic engagement,Health,Life Satisfaction,Safety,Work Life Balance,ny_gdp_pcap_pp_kd,GDP
0,AUS,0.780307,0.596762,0.761905,0.859389,0.890580,0.875000,0.928983,0.733333,0.618918,0.675631,0.384894,59552.880
1,AUT,0.591958,0.464477,0.714286,0.684137,0.771014,0.354787,0.776958,0.766667,0.928323,0.510156,0.430735,65015.133
2,BEL,0.718772,0.519196,0.619048,0.781322,0.577415,0.657447,0.806706,0.633333,0.634026,0.278489,0.423775,64185.848
3,BRA,0.579208,NaN,0.285714,0.205451,0.476329,0.622340,0.579208,0.400000,0.193786,0.204461,0.044713,19018.238
4,CAN,0.746823,0.531429,0.761905,0.790656,0.854106,0.669681,0.943069,0.700000,0.839694,0.460323,0.354397,55918.930

In [15]:
df_final['Promedio General']=df_final.iloc[:,1:11].mean(axis=1)
df_final.head()

,LOCATION,Housing,Income,Community,Education,Enviroment,Civic engagement,Health,Life Satisfaction,Safety,Work Life Balance,ny_gdp_pcap_pp_kd,GDP,Promedio General
0,AUS,0.780307,0.596762,0.761905,0.859389,0.890580,0.875000,0.928983,0.733333,0.618918,0.675631,0.384894,59552.880,0.772081
1,AUT,0.591958,0.464477,0.714286,0.684137,0.771014,0.354787,0.776958,0.766667,0.928323,0.510156,0.430735,65015.133,0.656276
2,BEL,0.718772,0.519196,0.619048,0.781322,0.577415,0.657447,0.806706,0.633333,0.634026,0.278489,0.423775,64185.848,0.622575
3,BRA,0.579208,NaN,0.285714,0.205451,0.476329,0.622340,0.579208,0.400000,0.193786,0.204461,0.044713,19018.238,0.394055
4,CAN,0.746823,0.531429,0.761905,0.790656,0.854106,0.669681,0.943069,0.700000,0.839694,0.460323,0.354397,55918.930,0.729769

In [16]:
america = ['BRA', 'CAN', 'CHL', 'COL', 'CRI', 'MEX', 'USA']
europa = ['AUT', 'BEL', 'CHE', 'CZE', 'DEU', 'DNK', 'ESP', 'EST', 'FIN', 'FRA', 'GBR', 'GRC', 'HUN', 'IRL', 'ISL', 'ITA', 'LTU', 'LUX', 'LVA', 'NLD', 'NOR', 'POL', 'PRT', 'RUS', 'SVK', 'SVN', 'SWE']
asia = ['ISR', 'JPN', 'KOR', 'TUR']
oceania = ['AUS', 'NZL']
africa = ['ZAF']
df_final["Continente"] = None
for index, x in enumerate(df_final["LOCATION"]): 
    if x in america:
        df_final.at[index, "Continente"] = "America" 
    elif x in europa:
        df_final.at[index, "Continente"] = "Europa"
    elif x in asia:
        df_final.at[index, "Continente"] = "Asia"
    elif x in oceania:
        df_final.at[index, "Continente"] = "Oceania"
    elif x in africa:
        df_final.at[index, "Continente"] = "Africa"

In [17]:
import plotly.express as px


fig = px.scatter(df_final,x='GDP',y='Promedio General',color='Continente',hover_name='LOCATION',size_max=60, title="Índice de bienestar vs PIB per cápita", trendline="ols", trendline_color_override="black", trendline_scope="overall")
fig.show()